plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Naming/MethodParameterName:
  MinNameLength: 1

Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
