Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 40

Naming/MethodParameterName:
  MinNameLength: 1

Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

