name: Run bundix on dependencies-labeled PRs
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  followup-bundix:
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      head_ref: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.head_ref }}
      - uses: DeterminateSystems/nix-installer-action@v18
        with:
          extra-conf: |
            cores = 0
      - uses: DeterminateSystems/magic-nix-cache-action@v12
      - run: nix run '.#bundix'
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Update gemset.nix via bundix'
